apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - pods/log
  - services
  - replicationcontrollers
  - secrets
  - configmaps
  - daemonsets
  - statefulsets
  - replicasets
  - jobs
  - cronjobs
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - networking.k8s.io
  resources:
    - ingresses
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-admin-binding
subjects:
- kind: Group
  name: eks-admin-group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eks-admin
  apiGroup: rbac.authorization.k8s.io
