name: Deploy to dev environment

on:
  push:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Helm Dependency Update
        run: helm dependency update
      - name: Merge Values
        run: |
          yq eval-all '. as $item ireduce ({}; . * $item )' \
          values/dev.yaml \
          values/openmrs/dev.yaml \
          values/bahmni-web/dev.yaml \
          > values.yaml
      - name: Authorise Kubectl with EKS
        run: aws eks update-kubeconfig --name $CLUSTER_NAME
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BAHMNI_AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BAHMNI_AWS_SECRET }}
          AWS_DEFAULT_REGION: ${{ secrets.BAHMNI_AWS_REGION }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      - name: Helm Upgrade
        run: |
          RDS_USERNAME=$(aws ssm get-parameter --with-decryption --name "RDS_USERNAME" --query "Parameter.Value" --output text) 
          RDS_PASSWORD=$(aws ssm get-parameter --with-decryption --name "RDS_PASSWORD" --query "Parameter.Value" --output text) 
          RDS_HOST=$(aws ssm get-parameter --with-decryption --name "RDS_HOST" --query "Parameter.Value" --output text) 
          INGRESS_HOST=$(aws ssm get-parameter --with-decryption --name "INGRESS_HOST" --query "Parameter.Value" --output text) 
          helm upgrade --install bahmni-dev . \
          --set openmrs.secrets.DB_USERNAME= $RDS_USERNAME \
          --set openmrs.secrets.DB_PASSWORD= $RDS_PASSWORD \
          --set openmrs.secrets.DB_HOST= $RDS_HOST \
          --set ingress.host= $INGRESS_HOST
