name: Deploy to dev environment

on:
  push:
    branches: [ main, BAH-1711 ]
  workflow_dispatch:  

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Helm Dependency Update
        run: helm dependency update
      - name: Merge Values
        run: |
          yq eval-all '. as $item ireduce ({}; . * $item )' \
          values/dev.yaml \
          values/openmrs/dev.yaml \
          values/bahmni-web/dev.yaml \
          > values.yaml
      - run: cat values.yaml
#      - name: Helm Upgrade
#        run: |
#          helm upgrade --install bahmni-dev \


